### ISSUE TITLE
Write test cases to test the service

### ISSUE THREAD

**Issue by YongchangLiu98** [devops-customers-squad/customers#11]
**As a** Member of the development team
**I need** Testcases
**So that** I can test the services

**Assumptions:**
- All services work correctly.
- There should be tests for each of Create, Read, Update, Delete, and List, traversing both happy paths and sad paths.

Acceptance Criteria:
I should see all the operations effective.

**Comment by ryanjcohen** [comment]
Should we mention tests.py, based on the assignment instructions?

**Comment by ryanjcohen** [comment]
Closing as we do not need a separate ticket for testing
