### ISSUE TITLE
manifest.yml is currently configured for lab-bluemix-cf, but instead needs to be configured for our specific application

### ISSUE THREAD

**Issue by ryanjcohen** [devops-customers-squad/customers#111]
**Describe the problem**
manifest.yml is configured for the lab-bluemix-cf set up during the lecture demo.

**Expected behavior**
Name and route in the .yml file need to be changed. 
Name should be nyu-customer-service-fall2101
Route should be nyu-customer-service-fall2101.ussouth.cf.appdomain.cloud

**Comment by YongchangLiu98** [comment]
Should it be nyu-customer-service-fall2021?

**Comment by YongchangLiu98** [comment]
Just noticed that I forgot to change the name of the service
