### ISSUE TITLE
Need the ability to list customers with same first/last names

### ISSUE THREAD

**Issue by Bobby-Zien** [devops-customers-squad/customers#44]
**As a** e-commerce service admin
**I need** the ability to query customers by their first/last names
**So that** I manage and query customers more efficiently

**Details & Assumptions:** 
* Need to return a JSON object representing the list of customers with the queried first/last name

**Acceptance Criteria:**

```gherkin
Given a valid JSON request body
When I call 'GET {our API url}/customers?first_name={first name}'
Then I should receive a 200 HTTP return code and a JSON object representing the list of customers with the specified first name

Given a valid JSON request body
When I call 'GET {our API url}/customers?last_name={first name}'
Then I should receive a 200 HTTP return code and a JSON object representing the list of customers with the specified last name
```

**Comment by ryanjcohen** [comment]
Functionality covered by linked pull request
