### ISSUE TITLE
Create a Python Flask Cloud Foundry application

### ISSUE THREAD

**Issue by ryanjcohen** [devops-customers-squad/customers#57]
**As a** developer 
**I need** the flask cloud foundry application
**So that** the public can use our cloud app

**Details & Assumptions:** 
* Application name: nyu-customer-servicce-fall2101
* Application URL will be: nyu-customer-service-fall2101.us-south.cf.appdomain.cloud

**Acceptance Criteria:**

```gherkin
Given that the Python flask cloud foundry application is created
When the team make changes to the app
Then public should see the changes by calling the application URL
```

**Comment by Bobby-Zien** [comment]
Added Details and AC
