### ISSUE TITLE
Update the  repository's Vagrantfile to download and install the IBM Cloud CLI 

### ISSUE THREAD

**Issue by ryanjcohen** [devops-customers-squad/customers#58]
**As a** developer 
**I need** to add IBM Cloud CLI to the Vagrant file
**So that** our VM can access our team IBM Cloud

**Details & Assumptions:** 
* When I do vagrant up, the VM automatically logs in to the team IBM Cloud

**Acceptance Criteria:**

```gherkin
Given that the Vagrantfile is correctly updated
When the I need to access the IBM Cloud
Then I should be able to connect to the IBM Cloud without manually logging in to the cloud
```

**Comment by Bobby-Zien** [comment]
Added Details and AC
