### ISSUE TITLE
Create the metadata files for deployment

### ISSUE THREAD

**Issue by ryanjcohen** [devops-customers-squad/customers#59]
**As a** developer 
**I need** create metadata files
**So that** IBM Cloud will know how to deploy our application

**Details & Assumptions:** 
* Create manifest.yml, Procfile, runtime.txt files based on https://github.com/nyu-devops/lab-bluemix-cf

**Acceptance Criteria:**

```gherkin
Given that the metadata files are created correctly
When I do ic cf push in the VM
Then the Cloud app should be deployed according to the metadata files.
```

**Comment by Bobby-Zien** [comment]
Added details and AC
