### ISSUE TITLE
Push the application to IBM Cloud

### ISSUE THREAD

**Issue by ryanjcohen** [devops-customers-squad/customers#62]
**As a** developer 
**I need** to push our application to IBM Cloud
**So that** the public can access our latest version of app

**Details & Assumptions:** 
* Use _**ibmcloud cf push to push**_ our application in the VM

**Acceptance Criteria:**

```gherkin
Given that the team add some features to our application
When I do ic cf push in the VM
Then the Cloud app will be re-deployed and it should have those new features
```

**Comment by Bobby-Zien** [comment]
Added details and AC
