### ISSUE TITLE
Need the ability to query specific customers from the UI

### ISSUE THREAD

**Issue by domejiraphon** [devops-customers-squad/customers#98]
**As a** store owner
**I need** ability to get specific group of customers
**So that** I can do targeted advertisement

**Details & Assumptions:** 
* Edit some.feature file with the following gherkin
* Edit steps.py to test this scenario

**Acceptance Criteria:**

```gherkin
Scenario 1: Query a group of customer
Given that I am a store owner
And I have 2 customers in my database with the first name "John"
When I enter "John" in the "First Name" field
And I press "Search Customers"
Then I should see two different customers named "John" in the search results
```

**Comment by ryanjcohen** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/dfa5f370-4610-4cc3-b00a-cc377cfff178?env_id=ibm:yp:us-south "customers-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/bcf906cc-f45b-4b30-a096-6ea68fc0ead1 "customers") deployed [customers](https://github.com/devops-customers-squad/customers/releases/tag/deploy-ibm-yp-us-south-rjc584-nyu.edu-dev-20211204-005505 "deploy-ibm-yp-us-south-rjc584-nyu.edu-dev-20211204-005505") to [dev](https://console.bluemix.net/apps/57207d43-2a44-4c6a-916f-347eb68fb4cc?env_id=ibm:yp:us-south "ibm:yp:us-south:rjc584+@nyu.edu:dev"), including commit c288149ff50a0731700cf243dcabf9694d492cd2
